#ifndef ILLUMINA_AST_H
#define ILLUMINA_AST_H

#include "common/util/generic_structs.h"

/*
 * Due to rapid changes in the frontend of the compiler,
 * a separate syntax tree is constructed independent of
 * the one generated by yacc.
 */

#define ATTR_HEADER

struct _node_program;
typedef struct _node_program node_program_t;

struct _node_import;
typedef struct _node_import node_import_t;

struct _node_class;
typedef struct _node_class node_class_t;

struct _node_func;
typedef struct _node_func node_func_t;

struct _node_prop;
typedef struct _node_prop node_prop_t;

struct _node_program {
    GEN_ARRAY_T(node_import_t) imports;
    GEN_ARRAY_T(node_class_t) classes;
    GEN_ARRAY_T(node_func_t) funcs;
};

struct _node_import {

};

struct _node_class {

};

struct _node_func {

};

#endif //ILLUMINA_AST_H
