#ifndef ILLUMINA_OP_LIT_H
#define ILLUMINA_OP_LIT_H

typedef enum {
    ASN, ASN_ADD, ASN_SUB, ASN_MUL, ASN_DIV, ASN_MOD, ASN_AND,
    ASN_XOR, ASN_OR, ASN_SHL, ASN_SHR,

    BIN_LOGIC_OR, BIN_LOGIC_AND, BIN_OR, BIN_AND, BIN_XOR,
    BIN_NEQ, BIN_EQ, BIN_LT, BIN_GT, BIN_LEQ, BIN_GEQ,

    BIN_SHL, BIN_SHR, BIN_ADD, BIN_SUB, BIN_MUL, BIN_DIV, BIN_MOD,
    BIN_POW, BIN_REF,

    UN_PREINC, UN_PREDEC, UN_POS, UN_NEG, UN_LOGIC_NOT, UN_NOT,
    UN_POSINC, UN_POSDEC
} op_t;

#endif //ILLUMINA_OP_LIT_H
